//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaFinal.servicioLogica {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Linea", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Linea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PruebaFinal.servicioLogica.Estacion[] estacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroTrenesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PruebaFinal.servicioLogica.Estacion[] estaciones {
            get {
                return this.estacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.estacionesField, value) != true)) {
                    this.estacionesField = value;
                    this.RaisePropertyChanged("estaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numeroTrenes {
            get {
                return this.numeroTrenesField;
            }
            set {
                if ((this.numeroTrenesField.Equals(value) != true)) {
                    this.numeroTrenesField = value;
                    this.RaisePropertyChanged("numeroTrenes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Estacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreEstacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoField, value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreEstacion {
            get {
                return this.nombreEstacionField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreEstacionField, value) != true)) {
                    this.nombreEstacionField = value;
                    this.RaisePropertyChanged("nombreEstacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrasbordoDoble", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class TrasbordoDoble : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estacion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estacion2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linea1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linea2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estacion1 {
            get {
                return this.estacion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.estacion1Field, value) != true)) {
                    this.estacion1Field = value;
                    this.RaisePropertyChanged("estacion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estacion2 {
            get {
                return this.estacion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.estacion2Field, value) != true)) {
                    this.estacion2Field = value;
                    this.RaisePropertyChanged("estacion2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linea1 {
            get {
                return this.linea1Field;
            }
            set {
                if ((object.ReferenceEquals(this.linea1Field, value) != true)) {
                    this.linea1Field = value;
                    this.RaisePropertyChanged("linea1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linea2 {
            get {
                return this.linea2Field;
            }
            set {
                if ((object.ReferenceEquals(this.linea2Field, value) != true)) {
                    this.linea2Field = value;
                    this.RaisePropertyChanged("linea2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrasbordoSimple", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class TrasbordoSimple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] lineasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estacion {
            get {
                return this.estacionField;
            }
            set {
                if ((object.ReferenceEquals(this.estacionField, value) != true)) {
                    this.estacionField = value;
                    this.RaisePropertyChanged("estacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] lineas {
            get {
                return this.lineasField;
            }
            set {
                if ((object.ReferenceEquals(this.lineasField, value) != true)) {
                    this.lineasField = value;
                    this.RaisePropertyChanged("lineas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Administrador", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Administrador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="servicioLogica.IServicioLogica")]
    public interface IServicioLogica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ValidarTextBoxNumeros", ReplyAction="http://tempuri.org/IServicioLogica/ValidarTextBoxNumerosResponse")]
        bool ValidarTextBoxNumeros(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ComprobarEstacion", ReplyAction="http://tempuri.org/IServicioLogica/ComprobarEstacionResponse")]
        bool ComprobarEstacion(string nombreLinea, string nombreEstacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ValidarNombres", ReplyAction="http://tempuri.org/IServicioLogica/ValidarNombresResponse")]
        string ValidarNombres(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/CrearLinea", ReplyAction="http://tempuri.org/IServicioLogica/CrearLineaResponse")]
        bool CrearLinea(string nombreLinea, int numeroTrenes, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/CrearEstacion", ReplyAction="http://tempuri.org/IServicioLogica/CrearEstacionResponse")]
        bool CrearEstacion(string nombreLinea, string estacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ModificarLinea", ReplyAction="http://tempuri.org/IServicioLogica/ModificarLineaResponse")]
        bool ModificarLinea(string nombreLinea, string nuevoNombre, int numeroTrenes, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerLinea", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerLineaResponse")]
        PruebaFinal.servicioLogica.Linea ObtenerLinea(string nombreLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerEstacion", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerEstacionResponse")]
        PruebaFinal.servicioLogica.Estacion ObtenerEstacion(string nombreLinea, string nombreEstacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ModificarEstacion", ReplyAction="http://tempuri.org/IServicioLogica/ModificarEstacionResponse")]
        bool ModificarEstacion(string nombreLinea, string estacion, string nuevaEstacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ModificarEstadoEstacion", ReplyAction="http://tempuri.org/IServicioLogica/ModificarEstadoEstacionResponse")]
        bool ModificarEstadoEstacion(string estacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ModificarEstadoLinea", ReplyAction="http://tempuri.org/IServicioLogica/ModificarEstadoLineaResponse")]
        bool ModificarEstadoLinea(string nombreLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/EliminarLinea", ReplyAction="http://tempuri.org/IServicioLogica/EliminarLineaResponse")]
        bool EliminarLinea(string nombreLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/EliminarEstacion", ReplyAction="http://tempuri.org/IServicioLogica/EliminarEstacionResponse")]
        bool EliminarEstacion(string nombreLinea, string estacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/CrearTrasbordoDoble", ReplyAction="http://tempuri.org/IServicioLogica/CrearTrasbordoDobleResponse")]
        bool CrearTrasbordoDoble(string linea1, string estacion1, string linea2, string estacion2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/CrearTrasbordoSimple", ReplyAction="http://tempuri.org/IServicioLogica/CrearTrasbordoSimpleResponse")]
        bool CrearTrasbordoSimple(string estacion, string[] lineas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/EliminarTrasbordoSimple", ReplyAction="http://tempuri.org/IServicioLogica/EliminarTrasbordoSimpleResponse")]
        bool EliminarTrasbordoSimple(string nombreEstacion, string nombreLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/EliminarTransbordoDoble", ReplyAction="http://tempuri.org/IServicioLogica/EliminarTransbordoDobleResponse")]
        bool EliminarTransbordoDoble(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerListaTrasbordoD", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerListaTrasbordoDResponse")]
        PruebaFinal.servicioLogica.TrasbordoDoble[] ObtenerListaTrasbordoD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerListaStringTransbordoD", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerListaStringTransbordoDResponse")]
        string[] ObtenerListaStringTransbordoD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerListaLineas", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerListaLineasResponse")]
        PruebaFinal.servicioLogica.Linea[] ObtenerListaLineas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerListaEstaciones", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerListaEstacionesResponse")]
        PruebaFinal.servicioLogica.Estacion[] ObtenerListaEstaciones(string nombreLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerListaTrasbordoS", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerListaTrasbordoSResponse")]
        PruebaFinal.servicioLogica.TrasbordoSimple[] ObtenerListaTrasbordoS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerTrasbordoS", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerTrasbordoSResponse")]
        PruebaFinal.servicioLogica.TrasbordoSimple ObtenerTrasbordoS(string estacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/LlenarTablaEstaciones", ReplyAction="http://tempuri.org/IServicioLogica/LlenarTablaEstacionesResponse")]
        System.Data.DataTable LlenarTablaEstaciones(string nombreLinea);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/LlenarTablaLineas", ReplyAction="http://tempuri.org/IServicioLogica/LlenarTablaLineasResponse")]
        System.Data.DataTable LlenarTablaLineas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/LlenarTablaTrasbordosDobles", ReplyAction="http://tempuri.org/IServicioLogica/LlenarTablaTrasbordosDoblesResponse")]
        System.Data.DataTable LlenarTablaTrasbordosDobles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ValidarUsuario", ReplyAction="http://tempuri.org/IServicioLogica/ValidarUsuarioResponse")]
        bool ValidarUsuario(string usuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ObtenerAdministrador", ReplyAction="http://tempuri.org/IServicioLogica/ObtenerAdministradorResponse")]
        PruebaFinal.servicioLogica.Administrador ObtenerAdministrador();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ModificarAdministrador", ReplyAction="http://tempuri.org/IServicioLogica/ModificarAdministradorResponse")]
        void ModificarAdministrador(PruebaFinal.servicioLogica.Administrador admin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ValidarTextBoxVacio", ReplyAction="http://tempuri.org/IServicioLogica/ValidarTextBoxVacioResponse")]
        bool ValidarTextBoxVacio(string cadena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioLogica/ValidarTextBoxCaracteresEsp", ReplyAction="http://tempuri.org/IServicioLogica/ValidarTextBoxCaracteresEspResponse")]
        bool ValidarTextBoxCaracteresEsp(string cadena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioLogicaChannel : PruebaFinal.servicioLogica.IServicioLogica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioLogicaClient : System.ServiceModel.ClientBase<PruebaFinal.servicioLogica.IServicioLogica>, PruebaFinal.servicioLogica.IServicioLogica {
        
        public ServicioLogicaClient() {
        }
        
        public ServicioLogicaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioLogicaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLogicaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioLogicaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarTextBoxNumeros(string cadena) {
            return base.Channel.ValidarTextBoxNumeros(cadena);
        }
        
        public bool ComprobarEstacion(string nombreLinea, string nombreEstacion) {
            return base.Channel.ComprobarEstacion(nombreLinea, nombreEstacion);
        }
        
        public string ValidarNombres(string cadena) {
            return base.Channel.ValidarNombres(cadena);
        }
        
        public bool CrearLinea(string nombreLinea, int numeroTrenes, string tipo) {
            return base.Channel.CrearLinea(nombreLinea, numeroTrenes, tipo);
        }
        
        public bool CrearEstacion(string nombreLinea, string estacion) {
            return base.Channel.CrearEstacion(nombreLinea, estacion);
        }
        
        public bool ModificarLinea(string nombreLinea, string nuevoNombre, int numeroTrenes, string tipo) {
            return base.Channel.ModificarLinea(nombreLinea, nuevoNombre, numeroTrenes, tipo);
        }
        
        public PruebaFinal.servicioLogica.Linea ObtenerLinea(string nombreLinea) {
            return base.Channel.ObtenerLinea(nombreLinea);
        }
        
        public PruebaFinal.servicioLogica.Estacion ObtenerEstacion(string nombreLinea, string nombreEstacion) {
            return base.Channel.ObtenerEstacion(nombreLinea, nombreEstacion);
        }
        
        public bool ModificarEstacion(string nombreLinea, string estacion, string nuevaEstacion) {
            return base.Channel.ModificarEstacion(nombreLinea, estacion, nuevaEstacion);
        }
        
        public bool ModificarEstadoEstacion(string estacion) {
            return base.Channel.ModificarEstadoEstacion(estacion);
        }
        
        public bool ModificarEstadoLinea(string nombreLinea) {
            return base.Channel.ModificarEstadoLinea(nombreLinea);
        }
        
        public bool EliminarLinea(string nombreLinea) {
            return base.Channel.EliminarLinea(nombreLinea);
        }
        
        public bool EliminarEstacion(string nombreLinea, string estacion) {
            return base.Channel.EliminarEstacion(nombreLinea, estacion);
        }
        
        public bool CrearTrasbordoDoble(string linea1, string estacion1, string linea2, string estacion2) {
            return base.Channel.CrearTrasbordoDoble(linea1, estacion1, linea2, estacion2);
        }
        
        public bool CrearTrasbordoSimple(string estacion, string[] lineas) {
            return base.Channel.CrearTrasbordoSimple(estacion, lineas);
        }
        
        public bool EliminarTrasbordoSimple(string nombreEstacion, string nombreLinea) {
            return base.Channel.EliminarTrasbordoSimple(nombreEstacion, nombreLinea);
        }
        
        public bool EliminarTransbordoDoble(string cadena) {
            return base.Channel.EliminarTransbordoDoble(cadena);
        }
        
        public PruebaFinal.servicioLogica.TrasbordoDoble[] ObtenerListaTrasbordoD() {
            return base.Channel.ObtenerListaTrasbordoD();
        }
        
        public string[] ObtenerListaStringTransbordoD() {
            return base.Channel.ObtenerListaStringTransbordoD();
        }
        
        public PruebaFinal.servicioLogica.Linea[] ObtenerListaLineas() {
            return base.Channel.ObtenerListaLineas();
        }
        
        public PruebaFinal.servicioLogica.Estacion[] ObtenerListaEstaciones(string nombreLinea) {
            return base.Channel.ObtenerListaEstaciones(nombreLinea);
        }
        
        public PruebaFinal.servicioLogica.TrasbordoSimple[] ObtenerListaTrasbordoS() {
            return base.Channel.ObtenerListaTrasbordoS();
        }
        
        public PruebaFinal.servicioLogica.TrasbordoSimple ObtenerTrasbordoS(string estacion) {
            return base.Channel.ObtenerTrasbordoS(estacion);
        }
        
        public System.Data.DataTable LlenarTablaEstaciones(string nombreLinea) {
            return base.Channel.LlenarTablaEstaciones(nombreLinea);
        }
        
        public System.Data.DataTable LlenarTablaLineas() {
            return base.Channel.LlenarTablaLineas();
        }
        
        public System.Data.DataTable LlenarTablaTrasbordosDobles() {
            return base.Channel.LlenarTablaTrasbordosDobles();
        }
        
        public bool ValidarUsuario(string usuario, string contraseña) {
            return base.Channel.ValidarUsuario(usuario, contraseña);
        }
        
        public PruebaFinal.servicioLogica.Administrador ObtenerAdministrador() {
            return base.Channel.ObtenerAdministrador();
        }
        
        public void ModificarAdministrador(PruebaFinal.servicioLogica.Administrador admin) {
            base.Channel.ModificarAdministrador(admin);
        }
        
        public bool ValidarTextBoxVacio(string cadena) {
            return base.Channel.ValidarTextBoxVacio(cadena);
        }
        
        public bool ValidarTextBoxCaracteresEsp(string cadena) {
            return base.Channel.ValidarTextBoxCaracteresEsp(cadena);
        }
    }
}
